Fix missing-prototypes
mpdclient.c:115:44: error: no previous prototype for 'xfmpc_mpdclient_get_type' [-Werror=missing-prototypes]
mpdclient.c:268:1: error: no previous prototype for 'xfmpc_mpdclient_get_default' [-Werror=missing-prototypes]
mpdclient.c:1234:1: error: no previous prototype for 'xfmpc_song_info_free' [-Werror=missing-prototypes]

Signed-off-by: Olaf Hering <olaf@aepfle.de>